name: Deploy bu docker

env:
  VPS_IP: 91.218.230.97
  VPS_USERNAME: root
  DIR: /home/docker
  GIT_BRANCH: origin/cicd_to_ihc_docker24

on:
  push:
    branches:
      - cicd_to_ihc_docker24

jobs:

  deploy:
    runs-on: ubuntu-latest
    outputs:
      rebuild_needed: ${{ steps.check_commit.outputs.rebuild_needed }}
      rebuild2503master: ${{ steps.check_commit.outputs.rebuild2503master }}
      rebuildCaddy: ${{ steps.check_commit.outputs.rebuildCaddy }}

    steps:
      - name: Check commit message
        id: check_commit
        run: |
          check_rebuild() {
            [[ "${{ github.event.head_commit.message }}" == *"[$1+"* ]] && echo "true" || echo "false"
          }
          
          echo "rebuild_needed=$(check_rebuild 'rebuild')" >> $GITHUB_OUTPUT
          echo "rebuild2503master=$(check_rebuild 'rebuild2503master')" >> $GITHUB_OUTPUT
          echo "rebuildCaddy=$(check_rebuild 'rebuildCaddy')" >> $GITHUB_OUTPUT

      - name: "Refresh git & base config"
        if: ${{ always() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY_DOCKER24 }}
          script: |
            cd ${{ env.DIR }}
            git fetch --all
            git reset --hard ${{ env.GIT_BRANCH }}

  deploy_composer:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Conditional steps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY_DOCKER24 }}
          script: |
            cd ${{ env.DIR }}
            
            echo ${{needs.deploy.outputs.rebuild_needed || 'x' }}
            echo ${{needs.deploy.outputs.rebuild2503master || 'x' }}
            echo ${{needs.deploy.outputs.rebuildCaddy || 'x' }}
            
            if [[ needs.deploy.outputs.rebuild2503master == 'true' ]]; then            
              echo "Rebuilding 2503master"
            else
              echo "Rebuilding 2503master -"
            fi
            
            
            ${{ needs.deploy.outputs.rebuild2503master == 'true' && 'echo "Rebuilding rebuild2503master" && make d-rebuild-2503master' || 'echo "Skipping 2503master rebuild"' }}

            if [ "${{ needs.deploy.outputs.rebuild_needed }}" == 'true' ]; then
              echo "Rebuilding"
              make prod
            else            
              echo "Rebuilding -"
            fi            
            
            #$#{{ needs.deploy.outputs.rebuild_needed == 'true' && 'echo "Full rebuild started" && make prod' || 'echo "Skipping full rebuild"' }}
                              
            if [ "${{ needs.deploy.outputs.rebuildCaddy }}" == 'true' ]; then
              echo "rebuildCaddy +"
              make caddy_refresh_cfd_prod
            else
              echo "rebuildCaddy -"
            fi

            #$#{{ needs.deploy.outputs.rebuildCaddy == 'true' && 'echo "Updating Caddy config" && docker-compose up -d caddy && docker cp ./caddy/Caddyfile caddy:/etc/caddy/Caddyfile && docker exec caddy caddy reload --config /etc/caddy/Caddyfile' || 'echo "Skipping Caddy update"' }}

  sms_end:
    runs-on: ubuntu-latest
    needs: [deploy_composer]
    steps:
      - name: send telega
        uses: appleboy/telegram-action@master
        with:
          to: 360209578, phpcat,
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🍀🍀🍀 Deployment Report
            Repo: ${{ github.repository }}
            Commit: ${{ github.event.head_commit.message || '-' }}
            By: ${{ github.actor }} (Run ID: ${{ github.run_id }})
            
            🔧 Rebuild Needed: ${{ needs.deploy.outputs.rebuild_needed || '--' }}
            🖥️ 2503master Rebuild: ${{ needs.deploy.outputs.rebuild2503master || '--' }}            
            🔐 Caddy Update: ${{ needs.deploy.outputs.rebuildCaddy || '--' }}
            if [ "${{ needs.deploy.outputs.rebuildCaddy }}" == 'true' ]; then rebuildCaddy+  fi